[book]
authors = ["Rynco Maekawa"]
language = "en"
multilingual = false
src = "src"
title = "NanoRs 指导书"

[output.html]
theme = "./theme"
default-theme = "city-lights"
additional-css = ["./theme/css/additional.css"]
mathjax-support = true

[output.html.fold]
enable = true
level = 2

[output.html.playpen]
enabled = false
copy-js = false
