[book]
authors = ["Rynco Maekawa"]
language = "en"
multilingual = false
src = "src"
title = "C0 指导书"

[output.html]
additional-css = ["./theme/css/additional.css"]
default-theme = "ayu"
mathjax-support = true
theme = "./theme"

[output.html.fold]
enable = true
level = 2

[output.html.playpen]
copy-js = false
enabled = false
