name: Deploy MdBook

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: XAMPPRocky/deploy-mdbook@v1
        with:
          workspace: "./docs/"
          token: ${{ secrets.GH_PAT }}
